# Generated by Django 5.2.6 on 2025-09-25 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('iddesafio', models.AutoField(primary_key=True, serialize=False)),
                ('nmdesafio', models.CharField(max_length=100)),
                ('dsdesafio', models.TextField()),
                ('dificuldade', models.CharField(choices=[('muito_facil', 'Muito fácil'), ('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('muito_dificil', 'Muito difícil')], max_length=20)),
                ('exprecompensa', models.SmallIntegerField()),
                ('dtcriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'desafios',
            },
        ),
        migrations.CreateModel(
            name='UsuarioDesafio',
            fields=[
                ('idusuariodesafio', models.AutoField(primary_key=True, serialize=False)),
                ('situacao', models.BooleanField(default=False)),
                ('dtpremiacao', models.DateField(blank=True, null=True)),
                ('iddesafio', models.ForeignKey(db_column='iddesafio', on_delete=django.db.models.deletion.CASCADE, to='desafios.desafio')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_desafios',
                'unique_together': {('idusuario', 'iddesafio')},
            },
        ),
    ]
