name: gamefymobile
description: "Um aplicativo para incentivar a produtividade"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # Garanta que esta linha tenha 2 espaços no início

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/avatares/
    - assets/conquistas/
  fonts:
    - family: Jersey 10
      fonts:
        - asset: assets/fonts/Jersey10-Regular.ttf